### ISSUE TITLE
Add red start next to required fields for different analysis

### ISSUE THREAD

**Issue by astha94** [web-mev/mev-frontend#12]
For the following analysis could we add what the required fields are so I can begin to add stars next to them:

Single-cell (SCTK):
Seurat clustering
SCTK UMAP dimensional reduction
MAST Single-cell differential expression

Normalization:
RNA-Seq normalization
Differential Expression
DESeq2
edgeR
Limma/voom

Pathways/networks:
Fast Gene Set Enrichment Analysis (fgsea)

Clustering:
Hierarchical clustering (HCL)
Principal component analysis (PCA)
K-means

Expression Boxplot 
Expression Heatmap

**Comment by blawney** [comment]
Added asterisks based on the `required` field as part of each operation specification. e527d76a914e6fac0b8a3ab5d5a7af5e27c780b6
