### ISSUE TITLE
Allow pasting of gene list to create feature set

### ISSUE THREAD

**Issue by blawney** [web-mev/mev-frontend#124]

**Comment by blawney** [comment]
When you click 'create a feature set' in the metadata tab, you have to manually type genes one by one. There are some instances where users might like to paste a list of genes. For instance, they can download gene sets from msigdb (https://www.gsea-msigdb.org/gsea/msigdb/cards/HALLMARK_ANDROGEN_RESPONSE.html) and then have a list of genes. They should be able to paste that, or the input box should be able to interpret that pasted list and behave accordingly.

**Comment by saronnhong** [comment]
This has been completed.
