### ISSUE TITLE
Create mock ups for the data filtering tool for web-mev

### ISSUE THREAD

**Issue by astha94** [web-mev/mev-frontend#13]
Add data files for data filtering which can be used to help mockup the data filtering tool

**Comment by blawney** [comment]
Added a couple example files in the example-data folder (https://github.com/web-mev/mev-frontend/pull/14).

Data will be queried via an API interface with a solr backend, but these files provide a concrete example of the data that solr will be indexing.

**Comment by blawney** [comment]
We have the interface now, so this issue is moot.
