### ISSUE TITLE
Ignore empty json in HCL output

### ISSUE THREAD

**Issue by blawney** [web-mev/mev-frontend#130]
Due to migration to AWS (and how it interacts with the Cromwell job runner), we are now obligated to output both observation *and* feature JSON-format files from our hierarchical clustering tool.

Previously, if a user selected "cluster on observations", there would *not* be a file for the feature clustering. Now there is, but it's effectively empty (e.g. `{}`). The frontend should see the empty tree and display a warning/message about that. At the moment, it displays just a single node, so it's not clear that this is expected.

**Comment by saronnhong** [comment]
This has been fixed.
