### ISSUE TITLE
Frontend component for likelihood ratio test

### ISSUE THREAD

**Issue by blawney** [web-mev/mev-frontend#134]
We need an "output" page for the new likelihood ratio test (LRT) analysis.

This is similar to the other differential gene expression output pages (deseq2, etc.) except for the following:
- the others compare two groups, which the user defines when they start the analysis

Here, the LRT performs comparison between N groups, where N is >=2 (and typically small, like < 5). 

Just like the other diff. exp components, we need the following on the output page:
- table of top genes
- boxplot

There are a couple small differences which need customization:
- The table (the file given by the `dge_results` key) has the following columns (which are *mostly* the same as the other DGE analyses):
    - `Gene`	
    - `baseMean`	
    - `log2FoldChange`	
    - `statistic`	
    - `pvalue`	
    - `padj`   
    - A bunch of other columns giving the normalized expression values for each sample

The p-value represents the significance of *any* differences between the groups. Since there are (in general) >=2 groups (most often 3 or more), we need to tell the user from which comparison the `log2FoldChange` column comes from. This is part of the outputs (when you query `/api/executed-operations/<UUID>/` with the key of `lfc_comparison`. It will be a string like "A vs B".

For the boxplot, the other DGE analyses show the comparison of the two groups. Here, since we have (in general) >=2 groups, it would be great to show that for them. For instance:
![image](https://user-images.githubusercontent.com/6886974/199010202-58d5f49a-676a-4e68-9564-e0ae840f5ac3.png)

(Code for this boxplot can mostly be derived from the boxplot plot component we already have)

The mapping of samples to groups can be found in the `sample_to_group_mapping` key in the outputs. This is a data structure like:
```
{
   "UHR": ["sampleA", "sampleB", ...],
   "HBR": ["sample1", "sample2", ...],
   "other": ["sampleY", "sampleZ", ...],
}
```
Users should be able to toggle whether they can see the individual samples (like the boxplot component we already have), but we should also have a button which will allow users to create observation sets based on `sample_to_group_mapping`.

**Comment by saronnhong** [comment]
Output page for Likelihood Ratio Test has been added.
