### ISSUE TITLE
Unable to log in after creating an account

### ISSUE THREAD

**Issue by jalilsharif** [web-mev/mev-frontend#158]
Hello, 

I created an account using my university and my personal email address, but it doesn't appear to work, I tried resetting the passwords, but that didn't do anything either, I also tried the offline app and that doesn't connect to the servers.

**Comment by blawney** [comment]
Hi there,

I apologize for the delay in reply (unsure why I did not receive a notification from GitHub). 

Thank you for letting us know-- the issue has been fixed and users have been notified. You may attempt to create a new account.
