### ISSUE TITLE
Add transient files to gitignore

### ISSUE THREAD

**Issue by hackdna** [web-mev/mev-frontend#18]
I'm seeing a few files that are the result of the "templating process". That is, files like `vagrant/env.txt` have config variables, etc. that are the result of editing `vagrant/env.tmpl`. 

In total, I see the following which should be removed from the latest commit:
- projects/web-mev/src/index.html
- projects/web-mev/src/app/jwtConfig.ts
- projects/web-mev/src/app/sentry-error-handler.ts
- projects/web-mev/src/environments/environment.ts

_Originally posted by @blawney in https://github.com/web-mev/mev-frontend/issues/17#issuecomment-896827734_

**Comment by blawney** [comment]
Addressed in aa64a255597e92f62302a10baf9abe60b24dc650
