### ISSUE TITLE
resource deletion not warning properly

### ISSUE THREAD

**Issue by blawney** [web-mev/mev-frontend#31]
If someone wants to delete a file that is associated with a workspace, the backend is properly reporting that the file cannot be deleted. The 204 response to the frontend also occurs. However, this failure to delete (and why) is not reported so it can lead to confusing/frustrating behavior for users.

**Comment by hackdna** [comment]
I think 403 Forbidden should be an appropriate response: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403

**Comment by blawney** [comment]
Backend changed to return 403 in commit 0cba55f7ef5cd588e5ef25df4b076f72ab706ad4.

Frontend catch and warning added in ec446c4d83f1e06c69899a084a8791fbbcd4a633
