### ISSUE TITLE
Add user input form

### ISSUE THREAD

**Issue by blawney** [web-mev/mev-frontend#50]
Create a user feedback form where users can tell us about bugs or features they would like. 

Need to link to this form prominently (in the upper banner?)

**Comment by saronnhong** [comment]
<img width="703" alt="Screen Shot 2022-04-04 at 9 42 56 AM" src="https://user-images.githubusercontent.com/50123485/161650758-b203ac1b-dc1d-4d55-8abf-4bb8d52f85b5.png">

**Comment by saronnhong** [comment]
This is done and merged onto the main branch.
