### ISSUE TITLE
"Group observations by" in Plotting/expression heatmap on the example RNASeq data results in whiting out the heatmap.

### ISSUE THREAD

**Issue by dkdeconti** [web-mev/mev-frontend#6]
Data was edgeR normalized matrix. Group observations by imported annotation file that was converted into observation sets (by import feature). Any selection of any of the group observations by checkboxes results in the whiteout of the boxplot. Heatmap visible if no observations selected.

**Comment by blawney** [comment]
Related to analyses mangling the observation names so they did not match.
