### ISSUE TITLE
"Group observations by" in Plotting/Expression boxplot on example RNASeq data results in actual boxplots disappearing.

### ISSUE THREAD

**Issue by dkdeconti** [web-mev/mev-frontend#7]
Data was edgeR normalized matrix. Group observations by imported annotation file that was converted into observation sets (by import feature). Any selection of any of the group observations by checkboxes results in the loss of the boxplot (however individual samples remain, but do not show appropriate spread). Boxplot visible if no observations selected.

**Comment by blawney** [comment]
Related to analyses mangling observation/sample names.
