### ISSUE TITLE
enlarge software host interface sizes

### ISSUE THREAD

**Issue by jackiee203** [web-mev/mev-frontend#80]
Dear developer,  could you please consider enlarge software host interface sizes when sign in the mev>?

**Comment by blawney** [comment]
Hi-- Can you please clarify what you mean by "host interface size"? The font size? If you can provide an example (picture), we can look at your request. Thank you

**Comment by jackiee203** [comment]
Hi, Thanks for your reply. the picture like this.



杜杰 Jackiee    非靶产品线总监
18817874110400-664-9912
***@***.***
www.biotree.cn; www.biotree.com.cn 
上海市嘉定区新培路51号焦点梦想园B栋5层，201815
邮件声明
本邮件仅为指定的收件者使用，其中可能包含保密的、专有的或享有合法特权的信息。若您并非指定的收件人，请勿使用、保留、泄露、转发、打印、复印本电子邮件或依据本邮件的内容而采取其他行动。如果您误收到本电子邮件，请立即与发送者联系，并请立即从邮箱及其他存储设备中删除这封邮件。谢谢！
 
From: Brian Lawney
Date: 2022-04-20 01:35
To: web-mev/mev-frontend
CC: jackiee203; Author
Subject: Re: [web-mev/mev-frontend] enlarge software host interface sizes (Issue #80)
Hi-- Can you please clarify what you mean by "host interface size"? The font size? If you can provide an example (picture), we can look at your request. Thank you

**Comment by blawney** [comment]
I do not see a picture in your reply. Maybe try again? thank you

**Comment by jackiee203** [comment]
Hi, the picture in the appendix.



杜杰 Jackiee    非靶产品线总监
18817874110400-664-9912
***@***.***
www.biotree.cn; www.biotree.com.cn 
上海市嘉定区新培路51号焦点梦想园B栋5层，201815
邮件声明
本邮件仅为指定的收件者使用，其中可能包含保密的、专有的或享有合法特权的信息。若您并非指定的收件人，请勿使用、保留、泄露、转发、打印、复印本电子邮件或依据本邮件的内容而采取其他行动。如果您误收到本电子邮件，请立即与发送者联系，并请立即从邮箱及其他存储设备中删除这封邮件。谢谢！
 
From: ***@***.***
Date: 2022-04-20 08:13
To: web-mev/mev-frontend; web-mev/mev-frontend
CC: Author
Subject: Re: Re: [web-mev/mev-frontend] enlarge software host interface sizes (Issue #80)
Hi, Thanks for your reply. the picture like this.



杜杰 Jackiee    非靶产品线总监
18817874110400-664-9912
***@***.***
www.biotree.cn; www.biotree.com.cn 
上海市嘉定区新培路51号焦点梦想园B栋5层，201815
邮件声明
本邮件仅为指定的收件者使用，其中可能包含保密的、专有的或享有合法特权的信息。若您并非指定的收件人，请勿使用、保留、泄露、转发、打印、复印本电子邮件或依据本邮件的内容而采取其他行动。如果您误收到本电子邮件，请立即与发送者联系，并请立即从邮箱及其他存储设备中删除这封邮件。谢谢！
 
From: Brian Lawney
Date: 2022-04-20 01:35
To: web-mev/mev-frontend
CC: jackiee203; Author
Subject: Re: [web-mev/mev-frontend] enlarge software host interface sizes (Issue #80)
Hi-- Can you please clarify what you mean by "host interface size"? The font size? If you can provide an example (picture), we can look at your request. Thank you

**Comment by blawney** [comment]
It seems you are replying with email. In that case, the pictures are not attached. I think you have to log onto the github.com site to upload a photo. Thanks!

**Comment by jackiee203** [comment]
[](url
![微信图片_20220420081041](https://user-images.githubusercontent.com/22786071/164347334-f5af27e5-7485-4398-9b3d-e7ed09fffa36.png)
)

**Comment by blawney** [comment]
OK, I now see the picture. Unfortunately, the software you are using is the old desktop version of MeV which is not supported or maintained anymore. 

The software we currently write and maintain are newer versions of MeV that are accessed through a web application at https://webmev.tm4.org. Many of the analyses are similar, although we focus more on RNA-seq instead of microarray.

**Comment by jackiee203** [comment]
OK，I get it.  Thanks



杜杰 Jackiee    非靶产品线总监
18817874110400-664-9912
***@***.***
www.biotree.cn; www.biotree.com.cn 
上海市嘉定区新培路51号焦点梦想园B栋5层，201815
邮件声明
本邮件仅为指定的收件者使用，其中可能包含保密的、专有的或享有合法特权的信息。若您并非指定的收件人，请勿使用、保留、泄露、转发、打印、复印本电子邮件或依据本邮件的内容而采取其他行动。如果您误收到本电子邮件，请立即与发送者联系，并请立即从邮箱及其他存储设备中删除这封邮件。谢谢！
 
From: Brian Lawney
Date: 2022-04-21 09:18
To: web-mev/mev-frontend
CC: jackiee203; Author
Subject: Re: [web-mev/mev-frontend] enlarge software host interface sizes (Issue #80)
OK, I now see the picture. Unfortunately, the software you are using is the old desktop version of MeV which is not supported or maintained anymore.
The software we currently write and maintain are newer versions of MeV that are accessed through a web application at https://webmev.tm4.org. Many of the analyses are similar, although we focus more on RNA-seq instead of microarray.
―

**Comment by jackiee203** [comment]
OK，thanks。



杜杰 Jackiee    非靶产品线总监
18817874110400-664-9912
***@***.***
www.biotree.cn; www.biotree.com.cn 
上海市嘉定区新培路51号焦点梦想园B栋5层，201815
邮件声明
本邮件仅为指定的收件者使用，其中可能包含保密的、专有的或享有合法特权的信息。若您并非指定的收件人，请勿使用、保留、泄露、转发、打印、复印本电子邮件或依据本邮件的内容而采取其他行动。如果您误收到本电子邮件，请立即与发送者联系，并请立即从邮箱及其他存储设备中删除这封邮件。谢谢！
 
From: Brian Lawney
Date: 2022-04-20 08:56
To: web-mev/mev-frontend
CC: jackiee203; Author
Subject: Re: [web-mev/mev-frontend] enlarge software host interface sizes (Issue #80)
It seems you are replying with email. In that case, the pictures are not attached. I think you have to log onto the github.com site to upload a photo. Thanks!
―
